# ---------- Build ----------
FROM node:18-alpine AS builder
WORKDIR /app
COPY backend/package*.json ./
RUN npm ci --production
COPY backend ./

# ---------- Runtime ----------
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app .
EXPOSE 4000
ENV NODE_ENV=production
CMD ["node", "server.js"]
